// async await works with promises

// let p = new Promise((resolve, reject) => {
//     let a = 1 + 1;
//     if(a == 2){
//         resolve('Success');
//     }else{
//         reject('Success');
//     }
// });

// // using promises
// // then is for resolve param
// // catch is for reject
// p.then((message) => {
//     console.log('This is in the then ' + message);
// }).catch((err) => {
//     console.log('This is in the catch' + err);
// });
